function [filterOutput] = speedfilter(filterProperties)

%SPEEDFILTER: defines a 3D filter for speed to be convolved
%with the fourier transform of a cube of white noise. Relies on parameters
%generated by the function specifyfilterproperties.m. 
%
%[Y1] = SPEEDFILTER(X1) takes a structure (X1) as input that
%specifies properties of the speed filter. 

end
